package resources

val effectNameToId = mapOf(
    "Shrinking" to 1,
    "Zombifying" to 2,
    "Cyclopean" to 3,
    "Anti-Gravity" to 4,
    "Long-Faced" to 5,
    "Electrifying" to 6,
    "Glowing" to 7,
    "Tropic-Thunder" to 8,
    "Thought-Provoking" to 9,
    "Jenerising" to 10,
    "Bright-Eyed" to 11,
    "Spicy" to 12,
    "Foggy" to 13,
    "Slippery" to 14,
    "Athletic" to 15,
    "Balding" to 16,
    "Calorie-Dense" to 17,
    "Sedating" to 18,
    "Sneaky" to 19,
    "Energizing" to 20,
    "Gingeritis" to 21,
    "Euphoric" to 22,
    "Focused" to 23,
    "Refreshing" to 24,
    "Munchies" to 25,
    "Calming" to 26,
    "Toxic" to 27,
    "Smelly" to 28,
    "Paranoia" to 29,
    "Schizophrenic" to 30,
    "Foggy" to 31,
    "Laxative" to 32,
    "Disorienting" to 33,
    "Explosive" to 34,
    "Seizure-Inducing" to 35,
)

val idToEffectName = effectNameToId.entries.associate { (k, v) -> v to k }