package resources

import datas.Material
import datas.RecipeRequirement

val rawMaterials:List<Material> = listOf(
    Material("OG-Kush", effectNameToId["Calming"]!!),
    Material("Sour-Diesel", effectNameToId["Refreshing"]!!),
    Material("Green-Crack", effectNameToId["Energizing"]!!),
    Material("Grandaddy-Purple", effectNameToId["Sedating"]!!)
)
val baseMaterials: List<Material> = listOf(
    Material("Cuke", effectNameToId["Energizing"]!!),
    Material("Banana", effectNameToId["Gingeritis"]!!),
    Material("Paracetamol", effectNameToId["Sneaky"]!!),
    Material("Donut", effectNameToId["Calorie-Dense"]!!),
    Material("Viagra", effectNameToId["Tropic-Thunder"]!!),
    Material("Mouth Wash", effectNameToId["Balding"]!!),
    Material("Flu Medicine", effectNameToId["Sedating"]!!),
    Material("Gasoline", effectNameToId["Toxic"]!!),
    Material("Energy Drink", effectNameToId["Athletic"]!!),
    Material("Motor Oil", effectNameToId["Slippery"]!!),
    Material("Mega Bean", effectNameToId["Foggy"]!!),
    Material("Chili", effectNameToId["Spicy"]!!),
    Material("Battery", effectNameToId["Bright-Eyed"]!!),
    Material("Iodine", effectNameToId["Jenerising"]!!),
    Material("Addy", effectNameToId["Thought-Provoking"]!!),
    Material("Horse Samen", effectNameToId["Long-Faced"]!!)
)
val requirements: List<RecipeRequirement> = listOf(
    // Energizing
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Energizing"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Banana", effectNameToId["Energizing"]!!),
    RecipeRequirement(effectNameToId["Paranoia"]!!, "Paracetamol", effectNameToId["Energizing"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Energizing"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Energizing"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Energizing"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Energizing"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Energizing"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Energizing"]!!),
    RecipeRequirement(effectNameToId["Euphoric"]!!, "Gasoline", effectNameToId["Energizing"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Energizing"]!!),
    RecipeRequirement(effectNameToId["Munchies"]!!, "Motor Oil", effectNameToId["Energizing"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Energizing"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Energizing"]!!),
    RecipeRequirement(effectNameToId["Cyclopean"]!!, "Mega Bean", effectNameToId["Energizing"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Energizing"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Energizing"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Energizing"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Energizing"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Energizing"]!!),

    // Gingeritis
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Gingeritis"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Cuke", effectNameToId["Gingeritis"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Gingeritis"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Gingeritis"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Gingeritis"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Gingeritis"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Gingeritis"]!!),
    RecipeRequirement(effectNameToId["Smelly"]!!, "Gasoline", effectNameToId["Gingeritis"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Gingeritis"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Gingeritis"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Gingeritis"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Gingeritis"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Gingeritis"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Gingeritis"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Gingeritis"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Gingeritis"]!!),
    RecipeRequirement(effectNameToId["Refreshing"]!!, "Horse Samen", effectNameToId["Gingeritis"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Gingeritis"]!!),

    // Sneaky
    RecipeRequirement(effectNameToId["Paranoia"]!!, "Cuke", effectNameToId["Sneaky"]!!),
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Sneaky"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Sneaky"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Sneaky"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Sneaky"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Sneaky"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Sneaky"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Sneaky"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Gasoline", effectNameToId["Sneaky"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Sneaky"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Sneaky"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Sneaky"]!!),
    RecipeRequirement(effectNameToId["Calming"]!!, "Mega Bean", effectNameToId["Sneaky"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Sneaky"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Chili", effectNameToId["Sneaky"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Sneaky"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Sneaky"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Sneaky"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Sneaky"]!!),

    // Calorie-Dense
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Calorie-Dense"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Calorie-Dense"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Calorie-Dense"]!!),
    RecipeRequirement(effectNameToId["Explosive"]!!, "Donut", effectNameToId["Calorie-Dense"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Calorie-Dense"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Calorie-Dense"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Mouth Wash", effectNameToId["Calorie-Dense"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Calorie-Dense"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Calorie-Dense"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Calorie-Dense"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Calorie-Dense"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Calorie-Dense"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Calorie-Dense"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Calorie-Dense"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Iodine", effectNameToId["Calorie-Dense"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Calorie-Dense"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Calorie-Dense"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Calorie-Dense"]!!),

    // Tropic-Thunder
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Tropic-Thunder"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Tropic-Thunder"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Tropic-Thunder"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Tropic-Thunder"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Tropic-Thunder"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Tropic-Thunder"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Tropic-Thunder"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Energy Drink", effectNameToId["Tropic-Thunder"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Tropic-Thunder"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Tropic-Thunder"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Tropic-Thunder"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Tropic-Thunder"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Tropic-Thunder"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Tropic-Thunder"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Tropic-Thunder"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Tropic-Thunder"]!!),

    // Balding
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Balding"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Balding"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Balding"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Donut", effectNameToId["Balding"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Balding"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Balding"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Balding"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Balding"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Balding"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Balding"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Balding"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Balding"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Balding"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Balding"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Balding"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Balding"]!!),

    // Sedating
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Sedating"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Sedating"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Sedating"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Sedating"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Sedating"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Sedating"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Sedating"]!!),
    RecipeRequirement(effectNameToId["Munchies"]!!, "Energy Drink", effectNameToId["Sedating"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Sedating"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Sedating"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Sedating"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Sedating"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Sedating"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Sedating"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Sedating"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Addy", effectNameToId["Sedating"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Sedating"]!!),

    // Toxic
    RecipeRequirement(effectNameToId["Euphoric"]!!, "Cuke", effectNameToId["Toxic"]!!),
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Toxic"]!!),
    RecipeRequirement(effectNameToId["Smelly"]!!, "Banana", effectNameToId["Toxic"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Toxic"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Toxic"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Paracetamol", effectNameToId["Toxic"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Toxic"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Toxic"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Toxic"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Toxic"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Toxic"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Toxic"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Toxic"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Toxic"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Toxic"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Iodine", effectNameToId["Toxic"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Toxic"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Toxic"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Toxic"]!!),

    // Athletic
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Athletic"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Athletic"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Athletic"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Athletic"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Viagra", effectNameToId["Athletic"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Athletic"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Athletic"]!!),
    RecipeRequirement(effectNameToId["Munchies"]!!, "Flu Medicine", effectNameToId["Athletic"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Athletic"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Athletic"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Athletic"]!!),
    RecipeRequirement(effectNameToId["Laxative"]!!, "Mega Bean", effectNameToId["Athletic"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Athletic"]!!),
    RecipeRequirement(effectNameToId["Euphoric"]!!, "Chili", effectNameToId["Athletic"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Athletic"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Athletic"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Athletic"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Athletic"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Athletic"]!!),

    // Slippery
    RecipeRequirement(effectNameToId["Munchies"]!!, "Cuke", effectNameToId["Slippery"]!!),
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Slippery"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Slippery"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Slippery"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Slippery"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Slippery"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Slippery"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Slippery"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Slippery"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Slippery"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Mega Bean", effectNameToId["Slippery"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Slippery"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Slippery"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Slippery"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Slippery"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Slippery"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Slippery"]!!),

    // Foggy
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Foggy"]!!),
    RecipeRequirement(effectNameToId["Cyclopean"]!!, "Cuke", effectNameToId["Foggy"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Foggy"]!!),
    RecipeRequirement(effectNameToId["Calming"]!!, "Paracetamol", effectNameToId["Foggy"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Foggy"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Foggy"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Foggy"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Foggy"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Foggy"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Foggy"]!!),
    RecipeRequirement(effectNameToId["Laxative"]!!, "Energy Drink", effectNameToId["Foggy"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Foggy"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Motor Oil", effectNameToId["Foggy"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Foggy"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Foggy"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Foggy"]!!),
    RecipeRequirement(effectNameToId["Paranoia"]!!, "Iodine", effectNameToId["Foggy"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Foggy"]!!),
    RecipeRequirement(effectNameToId["Energizing"]!!, "Addy", effectNameToId["Foggy"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Foggy"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Foggy"]!!),

    // Spicy
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Spicy"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Spicy"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Spicy"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Paracetamol", effectNameToId["Spicy"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Spicy"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Spicy"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Spicy"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Spicy"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Spicy"]!!),
    RecipeRequirement(effectNameToId["Euphoric"]!!, "Energy Drink", effectNameToId["Spicy"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Spicy"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Spicy"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Spicy"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Spicy"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Spicy"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Spicy"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Spicy"]!!),

    // Bright-Eyed
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Bright-Eyed"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Bright-Eyed"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Bright-Eyed"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Bright-Eyed"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Bright-Eyed"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Bright-Eyed"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Bright-Eyed"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Bright-Eyed"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Bright-Eyed"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Bright-Eyed"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Bright-Eyed"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Bright-Eyed"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Bright-Eyed"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Bright-Eyed"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Bright-Eyed"]!!),

    // Jenerising
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Jenerising"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Jenerising"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Jenerising"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Donut", effectNameToId["Jenerising"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Jenerising"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Jenerising"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Jenerising"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Jenerising"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Gasoline", effectNameToId["Jenerising"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Jenerising"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Jenerising"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Jenerising"]!!),
    RecipeRequirement(effectNameToId["Paranoia"]!!, "Mega Bean", effectNameToId["Jenerising"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Jenerising"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Jenerising"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Jenerising"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Jenerising"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Jenerising"]!!),

    // Thought-Provoking
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Thought-Provoking"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Thought-Provoking"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Thought-Provoking"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Thought-Provoking"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Thought-Provoking"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Thought-Provoking"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Flu Medicine", effectNameToId["Thought-Provoking"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Thought-Provoking"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Thought-Provoking"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Thought-Provoking"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Thought-Provoking"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Thought-Provoking"]!!),
    RecipeRequirement(effectNameToId["Energizing"]!!, "Mega Bean", effectNameToId["Thought-Provoking"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Thought-Provoking"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Thought-Provoking"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Thought-Provoking"]!!),
    RecipeRequirement(effectNameToId["Electrifying"]!!, "Horse Samen", effectNameToId["Thought-Provoking"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Thought-Provoking"]!!),

    // Long-Faced
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Long-Faced"]!!),
    RecipeRequirement(effectNameToId["Refreshing"]!!, "Banana", effectNameToId["Long-Faced"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Long-Faced"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Long-Faced"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Long-Faced"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Long-Faced"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Long-Faced"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Long-Faced"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Long-Faced"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Long-Faced"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Long-Faced"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Long-Faced"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Long-Faced"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Long-Faced"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Long-Faced"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Long-Faced"]!!),
    RecipeRequirement(effectNameToId["Electrifying"]!!, "Addy", effectNameToId["Long-Faced"]!!),

    // Calming
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Banana", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Paracetamol", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Anti-Gravity"]!!, "Mouth Wash", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Flu Medicine", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Glowing"]!!, "Mega Bean", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Iodine", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Calming"]!!),

    // Refreshing
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Refreshing"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Refreshing"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Refreshing"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Refreshing"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Refreshing"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Refreshing"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Refreshing"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Refreshing"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Refreshing"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Refreshing"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Refreshing"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Refreshing"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Refreshing"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Iodine", effectNameToId["Refreshing"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Refreshing"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Refreshing"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Refreshing"]!!),

    // Anti-Gravity
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Anti-Gravity"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Anti-Gravity"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Anti-Gravity"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Donut", effectNameToId["Anti-Gravity"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Anti-Gravity"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Anti-Gravity"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Anti-Gravity"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Anti-Gravity"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Anti-Gravity"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Anti-Gravity"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Anti-Gravity"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Anti-Gravity"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Anti-Gravity"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Chili", effectNameToId["Anti-Gravity"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Anti-Gravity"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Anti-Gravity"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Anti-Gravity"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Anti-Gravity"]!!),
    RecipeRequirement(effectNameToId["Calming"]!!, "Horse Samen", effectNameToId["Anti-Gravity"]!!),

    // Glowing
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Glowing"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Glowing"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Paracetamol", effectNameToId["Glowing"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Glowing"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Glowing"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Glowing"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Glowing"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Glowing"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Glowing"]!!),
    RecipeRequirement(effectNameToId["Disorienting"]!!, "Energy Drink", effectNameToId["Glowing"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Glowing"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Glowing"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Glowing"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Glowing"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Glowing"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Glowing"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Glowing"]!!),
    RecipeRequirement(effectNameToId["Refreshing"]!!, "Addy", effectNameToId["Glowing"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Glowing"]!!),

    // Paranoia
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Paranoia"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Paranoia"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Banana", effectNameToId["Paranoia"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Paracetamol", effectNameToId["Paranoia"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Paranoia"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Paranoia"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Paranoia"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Paranoia"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Paranoia"]!!),
    RecipeRequirement(effectNameToId["Calming"]!!, "Gasoline", effectNameToId["Paranoia"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Paranoia"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Paranoia"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Paranoia"]!!),
    RecipeRequirement(effectNameToId["Anti-Gravity"]!!, "Motor Oil", effectNameToId["Paranoia"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Paranoia"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Paranoia"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Paranoia"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Paranoia"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Paranoia"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Paranoia"]!!),

    // Euphoric
    RecipeRequirement(effectNameToId["Laxative"]!!, "Cuke", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Viagra", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Flu Medicine", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Motor Oil", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Zombifying"]!!, "Battery", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Seizure-Inducing"]!!, "Iodine", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Euphoric"]!!),

    // Munchies
    RecipeRequirement(effectNameToId["Athletic"]!!, "Cuke", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Anti-Gravity"]!!, "Paracetamol", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Calming"]!!, "Donut", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Flu Medicine", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Schizophrenic"]!!, "Motor Oil", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Chili", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Battery", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Munchies"]!!),

    // Cyclopean
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Cyclopean"]!!),
    RecipeRequirement(effectNameToId["Energizing"]!!, "Banana", effectNameToId["Cyclopean"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Cyclopean"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Cyclopean"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Cyclopean"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Cyclopean"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Cyclopean"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Cyclopean"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Cyclopean"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Cyclopean"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Cyclopean"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Cyclopean"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Cyclopean"]!!),
    RecipeRequirement(effectNameToId["Glowing"]!!, "Battery", effectNameToId["Cyclopean"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Cyclopean"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Cyclopean"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Cyclopean"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Cyclopean"]!!),

    // Laxative
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Laxative"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Laxative"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Laxative"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Laxative"]!!),
    RecipeRequirement(effectNameToId["Calming"]!!, "Viagra", effectNameToId["Laxative"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Laxative"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Laxative"]!!),
    RecipeRequirement(effectNameToId["Euphoric"]!!, "Flu Medicine", effectNameToId["Laxative"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Laxative"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Laxative"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Gasoline", effectNameToId["Laxative"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Laxative"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Laxative"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Laxative"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Chili", effectNameToId["Laxative"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Laxative"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Battery", effectNameToId["Laxative"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Laxative"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Laxative"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Laxative"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Laxative"]!!),

    // Smelly
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Smelly"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Smelly"]!!),
    RecipeRequirement(effectNameToId["Anti-Gravity"]!!, "Banana", effectNameToId["Smelly"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Smelly"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Smelly"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Smelly"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Smelly"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Smelly"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Smelly"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Smelly"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Smelly"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Smelly"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Smelly"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Smelly"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Smelly"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Smelly"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Smelly"]!!),

    // Explosive
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Explosive"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Explosive"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Explosive"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Explosive"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Explosive"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Mouth Wash", effectNameToId["Explosive"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Explosive"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Explosive"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Explosive"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Explosive"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Explosive"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Explosive"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Explosive"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Explosive"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Explosive"]!!),
    RecipeRequirement(effectNameToId["Euphoric"]!!, "Addy", effectNameToId["Explosive"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Explosive"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Explosive"]!!),

    // Electrifying
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Electrifying"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Electrifying"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Paracetamol", effectNameToId["Electrifying"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Electrifying"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Electrifying"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Electrifying"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Electrifying"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Electrifying"]!!),
    RecipeRequirement(effectNameToId["Refreshing"]!!, "Flu Medicine", effectNameToId["Electrifying"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Electrifying"]!!),
    RecipeRequirement(effectNameToId["Disorienting"]!!, "Gasoline", effectNameToId["Electrifying"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Electrifying"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Electrifying"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Electrifying"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Electrifying"]!!),
    RecipeRequirement(effectNameToId["Euphoric"]!!, "Battery", effectNameToId["Electrifying"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Electrifying"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Electrifying"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Electrifying"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Electrifying"]!!),

    // Disorienting
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Disorienting"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Disorienting"]!!),
    RecipeRequirement(effectNameToId["Focused"]!!, "Banana", effectNameToId["Disorienting"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Disorienting"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Disorienting"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Viagra", effectNameToId["Disorienting"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Disorienting"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Disorienting"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Disorienting"]!!),
    RecipeRequirement(effectNameToId["Glowing"]!!, "Gasoline", effectNameToId["Disorienting"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Disorienting"]!!),
    RecipeRequirement(effectNameToId["Electrifying"]!!, "Energy Drink", effectNameToId["Disorienting"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Disorienting"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Disorienting"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Disorienting"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Disorienting"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Disorienting"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Disorienting"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Disorienting"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Disorienting"]!!),

    // Seizure-Inducing
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Seizure-Inducing"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Seizure-Inducing"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Seizure-Inducing"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Seizure-Inducing"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Seizure-Inducing"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Seizure-Inducing"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Seizure-Inducing"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Seizure-Inducing"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Seizure-Inducing"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Seizure-Inducing"]!!),
    RecipeRequirement(effectNameToId["Focused"]!!, "Mega Bean", effectNameToId["Seizure-Inducing"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Seizure-Inducing"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Seizure-Inducing"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Seizure-Inducing"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Seizure-Inducing"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Seizure-Inducing"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Seizure-Inducing"]!!),
    RecipeRequirement(effectNameToId["Energizing"]!!, "Horse Samen", effectNameToId["Seizure-Inducing"]!!),

    // Zombifying
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Zombifying"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Zombifying"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Zombifying"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Zombifying"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Zombifying"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Zombifying"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Zombifying"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Zombifying"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Zombifying"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Zombifying"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Zombifying"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Zombifying"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Zombifying"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Zombifying"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Zombifying"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Zombifying"]!!),

    // Schizophrenic
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Schizophrenic"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Schizophrenic"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Schizophrenic"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Schizophrenic"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Schizophrenic"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Schizophrenic"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Schizophrenic"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Schizophrenic"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Energy Drink", effectNameToId["Schizophrenic"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Schizophrenic"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Schizophrenic"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Schizophrenic"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Schizophrenic"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Schizophrenic"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Schizophrenic"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Schizophrenic"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Schizophrenic"]!!),

    // Focused
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Seizure-Inducing"]!!, "Banana", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Paracetamol", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Euphoric"]!!, "Donut", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Mouth Wash", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Flu Medicine", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Shrinking"]!!, "Energy Drink", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Disorienting"]!!, "Mega Bean", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Focused"]!!),

    // Shrinking
    RecipeRequirement(effectNameToId["Energizing"]!!, "Cuke", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Banana", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Paracetamol", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Donut", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Energizing"]!!, "Donut", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Viagra", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Mouth Wash", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Paranoia"]!!, "Flu Medicine", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Flu Medicine", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Focused"]!!, "Gasoline", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Gasoline", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Energy Drink", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Motor Oil", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Mega Bean", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Electrifying"]!!, "Mega Bean", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Refreshing"]!!, "Chili", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Chili", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Munchies"]!!, "Battery", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Battery", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Iodine", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Addy", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Horse Samen", effectNameToId["Shrinking"]!!)
)
