package resources

import datas.Material
import datas.RecipeRequirement

val rawMaterials:List<Material> = listOf(
    Material("OG-Kush", effectNameToId["Calming"]!!),
    Material("Sour-Diesel", effectNameToId["Refreshing"]!!),
    Material("Green-Crack", effectNameToId["Energizing"]!!),
    Material("Grandaddy-Purple", effectNameToId["Sedating"]!!)
)
val baseMaterials: List<Material> = listOf(
    Material("Cuke", effectNameToId["Energizing"]!!),
    Material("Banana", effectNameToId["Gingeritis"]!!),
    Material("Paracetamol", effectNameToId["Sneaky"]!!),
    Material("Donut", effectNameToId["Calorie-Dense"]!!),
    Material("Viagra", effectNameToId["Tropic-Thunder"]!!),
    Material("Mouth Wash", effectNameToId["Balding"]!!),
    Material("Flu Medicine", effectNameToId["Sedating"]!!),
    Material("Gasoline", effectNameToId["Toxic"]!!),
    Material("Energy Drink", effectNameToId["Athletic"]!!),
    Material("Motor Oil", effectNameToId["Slippery"]!!),
    Material("Mega Bean", effectNameToId["Foggy"]!!),
    Material("Chili", effectNameToId["Spicy"]!!),
    Material("Battery", effectNameToId["Bright-Eyed"]!!),
    Material("Iodine", effectNameToId["Jenerising"]!!),
    Material("Addy", effectNameToId["Thought-Provoking"]!!),
    Material("Horse Samen", effectNameToId["Long-Faced"]!!)
)
val requirements: List<RecipeRequirement> = listOf(
    RecipeRequirement(effectNameToId["Anti-Gravity"]!!, "Banana", effectNameToId["Smelly"]!!),
    RecipeRequirement(effectNameToId["Anti-Gravity"]!!, "Paracetamol", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Anti-Gravity"]!!, "Mouth Wash", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Anti-Gravity"]!!, "Motor Oil", effectNameToId["Paranoia"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Cuke", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Athletic"]!!, "Cuke", effectNameToId["Slippery"]!!, includeEffectId = effectNameToId["Munchies"]), // if Munchies is already in the mix,
    RecipeRequirement(effectNameToId["Athletic"]!!, "Paracetamol", effectNameToId["Electrifying"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Paracetamol", effectNameToId["Paranoia"]!!),
    RecipeRequirement(effectNameToId["Balding"]!!, "Paracetamol", effectNameToId["Energizing"]!!, excludeEffectId = effectNameToId["Paranoia"]), // only when Paranoia isn't already in the mix,
    RecipeRequirement(effectNameToId["Balding"]!!, "Energy Drink", effectNameToId["Schizophrenic"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Paracetamol", effectNameToId["Spicy"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Viagra", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Flu Medicine", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Bright-Eyed"]!!, "Chili", effectNameToId["Sneaky"]!!),
    RecipeRequirement(effectNameToId["Calming"]!!, "Paracetamol", effectNameToId["Foggy"]!!),
    RecipeRequirement(effectNameToId["Calming"]!!, "V*agra", effectNameToId["Laxative"]!!),
    RecipeRequirement(effectNameToId["Calming"]!!, "Flu Medicine", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Calming"]!!, "Gasoline", effectNameToId["Paranoia"]!!),
    RecipeRequirement(effectNameToId["Calming"]!!, "Mega Bean", effectNameToId["Sneaky"]!!),
    RecipeRequirement(effectNameToId["Calming"]!!, "Horse Samen", effectNameToId["Anti-Gravity"]!!),
    RecipeRequirement(effectNameToId["Calorie-Dense"]!!, "Battery", effectNameToId["Laxative"]!!),
    RecipeRequirement(effectNameToId["Cyclopean"]!!, "Cuke", effectNameToId["Foggy"]!!),
    RecipeRequirement(effectNameToId["Cyclopean"]!!, "Mega Bean", effectNameToId["Thought-Provoking"]!!),
    RecipeRequirement(effectNameToId["Cyclopean"]!!, "Mega Bean", effectNameToId["Energizing"]!!, excludeEffectId = effectNameToId["Thought-Provoking"]), // when Thought-Provoking isn't already in the mix,
    RecipeRequirement(effectNameToId["Disorienting"]!!, "Gasoline", effectNameToId["Electrifying"]!!),
    RecipeRequirement(effectNameToId["Disorienting"]!!, "Mega Bean", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Disorienting"]!!, "Energy Drink", effectNameToId["Glowing"]!!),
    RecipeRequirement(effectNameToId["Electrifying"]!!, "Mega Bean", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Electrifying"]!!, "Energy Drink", effectNameToId["Disorienting"]!!),
    RecipeRequirement(effectNameToId["Electrifying"]!!, "Addy", effectNameToId["Long-Faced"]!!),
    RecipeRequirement(effectNameToId["Electrifying"]!!, "Horse S*men", effectNameToId["Thought-Provoking"]!!),
    RecipeRequirement(effectNameToId["Energizing"]!!, "Donut", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Energizing"]!!, "Mega Bean", effectNameToId["Thought-Provoking"]!!),
    RecipeRequirement(effectNameToId["Energizing"]!!, "Energy Drink", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Energizing"]!!, "Addy", effectNameToId["Foggy"]!!),
    RecipeRequirement(effectNameToId["Euphoric"]!!, "Cuke", effectNameToId["Toxic"]!!),
    RecipeRequirement(effectNameToId["Euphoric"]!!, "Donut", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Euphoric"]!!, "Flu Medicine", effectNameToId["Laxative"]!!),
    RecipeRequirement(effectNameToId["Euphoric"]!!, "Gasoline", effectNameToId["Energizing"]!!),
    RecipeRequirement(effectNameToId["Euphoric"]!!, "Energy Drink", effectNameToId["Spicy"]!!),
    RecipeRequirement(effectNameToId["Euphoric"]!!, "Chili", effectNameToId["Athletic"]!!),
    RecipeRequirement(effectNameToId["Euphoric"]!!, "Battery", effectNameToId["Electrifying"]!!, excludeEffectId = effectNameToId["Zombifying"]), // when Zombifying isn't already in the mix,
    RecipeRequirement(effectNameToId["Euphoric"]!!, "Addy", effectNameToId["Explosive"]!!),
    RecipeRequirement(effectNameToId["Explosive"]!!, "Donut", effectNameToId["Calorie-Dense"]!!),
    RecipeRequirement(effectNameToId["Focused"]!!, "Banana", effectNameToId["Disorienting"]!!),
    RecipeRequirement(effectNameToId["Focused"]!!, "Gasoline", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Focused"]!!, "Mega Bean", effectNameToId["Seizure-Inducing"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Flu Medicine", effectNameToId["Cyclopean"]!!),
    RecipeRequirement(effectNameToId["Foggy"]!!, "Gasoline", effectNameToId["Laxative"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Donut", effectNameToId["Jenerising"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Paracetamol", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Flu Medicine", effectNameToId["Thought-Provoking"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Iodine", effectNameToId["Calorie-Dense"]!!),
    RecipeRequirement(effectNameToId["Gingeritis"]!!, "Addy", effectNameToId["Sedating"]!!),
    RecipeRequirement(effectNameToId["Glowing"]!!, "Gasoline", effectNameToId["Disorienting"]!!),
    RecipeRequirement(effectNameToId["Glowing"]!!, "Mega Bean", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Glowing"]!!, "Mega Bean", effectNameToId["Sneaky"]!!, includeEffectId = effectNameToId["Calming"]),
    RecipeRequirement(effectNameToId["Glowing"]!!, "Battery", effectNameToId["Cyclopean"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Banana", effectNameToId["Paranoia"]!!),
    RecipeRequirement(effectNameToId["Jenerising"]!!, "Mouth Wash", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Laxative"]!!, "Cuke", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Laxative"]!!, "Energy Drink", effectNameToId["Foggy"]!!),
    RecipeRequirement(effectNameToId["Laxative"]!!, "Mega Bean", effectNameToId["Athletic"]!!),
    RecipeRequirement(effectNameToId["Long-Faced"]!!, "Chili", effectNameToId["Laxative"]!!),
    RecipeRequirement(effectNameToId["Munchies"]!!, "Cuke", effectNameToId["Slippery"]!!),
    RecipeRequirement(effectNameToId["Munchies"]!!, "Flu Medicine", effectNameToId["Athletic"]!!),
    RecipeRequirement(effectNameToId["Munchies"]!!, "Energy Drink", effectNameToId["Sedating"]!!),
    RecipeRequirement(effectNameToId["Munchies"]!!, "Motor Oil", effectNameToId["Energizing"]!!),
    RecipeRequirement(effectNameToId["Munchies"]!!, "Battery", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Paranoia"]!!, "Cuke", effectNameToId["Sneaky"]!!),
    RecipeRequirement(effectNameToId["Paranoia"]!!, "Paracetamol", effectNameToId["Energizing"]!!), // only if Munchies aren't already in the mix,
    RecipeRequirement(effectNameToId["Paranoia"]!!, "Flu Medicine", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Paranoia"]!!, "Mega Bean", effectNameToId["Jenerising"]!!),
    RecipeRequirement(effectNameToId["Paranoia"]!!, "Iodine", effectNameToId["Foggy"]!!),
    RecipeRequirement(effectNameToId["Refreshing"]!!, "Banana", effectNameToId["Long-Faced"]!!),
    RecipeRequirement(effectNameToId["Refreshing"]!!, "Flu Medicine", effectNameToId["Electrifying"]!!),
    RecipeRequirement(effectNameToId["Refreshing"]!!, "Chili", effectNameToId["Shrinking"]!!),
    RecipeRequirement(effectNameToId["Refreshing"]!!, "Addy", effectNameToId["Glowing"]!!),
    RecipeRequirement(effectNameToId["Refreshing"]!!, "Horse Samen", effectNameToId["Gingeritis"]!!),
    RecipeRequirement(effectNameToId["Schizophrenic"]!!, "Motor Oil", effectNameToId["Energizing"]!!),
    RecipeRequirement(effectNameToId["Schizophrenic"]!!, "Motor Oil", effectNameToId["Munchies"]!!, excludeEffectId = effectNameToId["Energizing"]), // only when Energizing isn't already in the mix,
    RecipeRequirement(effectNameToId["Sedating"]!!, "Iodine", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Mouth Wash", effectNameToId["Explosive"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Gasoline", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Sedating"]!!, "Motor Oil", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Seizure-Inducing"]!!, "Banana", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Seizure-Inducing"]!!, "Iodine", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Shrinking"]!!, "Energy Drink", effectNameToId["Focused"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Paracetamol", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Donut", effectNameToId["Anti-Gravity"]!!),
    RecipeRequirement(effectNameToId["Slippery"]!!, "Flu Medicine", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Smelly"]!!, "Banana", effectNameToId["Toxic"]!!),
    RecipeRequirement(effectNameToId["Smelly"]!!, "Gasoline", effectNameToId["Gingeritis"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Banana", effectNameToId["Calming"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Donut", effectNameToId["Balding"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Viagra", effectNameToId["Athletic"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Mouth Wash", effectNameToId["Calorie-Dense"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Gasoline", effectNameToId["Jenerising"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Energy Drink", effectNameToId["Tropic-Thunder"]!!),
    RecipeRequirement(effectNameToId["Sneaky"]!!, "Iodine", effectNameToId["Toxic"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Gasoline", effectNameToId["Energizing"]!!),
    RecipeRequirement(effectNameToId["Spicy"]!!, "Gasoline", effectNameToId["Euphoric"]!!, excludeEffectId = effectNameToId["Energizing"]), // only if Energizing isn't already in the mix,
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Cuke", effectNameToId["Gingeritis"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Banana", effectNameToId["Cyclopean"]!!),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Banana", effectNameToId["Energizing"]!!, includeEffectId = effectNameToId["Cyclopean"]),
    RecipeRequirement(effectNameToId["Thought-Provoking"]!!, "Iodine", effectNameToId["Refreshing"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Paracetamol", effectNameToId["Glowing"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Viagra", effectNameToId["Disorienting"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Chili", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Mega Bean", effectNameToId["Slippery"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Motor Oil", effectNameToId["Foggy"]!!),
    RecipeRequirement(effectNameToId["Toxic"]!!, "Flu Medicine", effectNameToId["Euphoric"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Paracetamol", effectNameToId["Toxic"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Gasoline", effectNameToId["Sneaky"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Chili", effectNameToId["Anti-Gravity"]!!),
    RecipeRequirement(effectNameToId["Tropic-Thunder"]!!, "Battery", effectNameToId["Munchies"]!!),
    RecipeRequirement(effectNameToId["Zombifying"]!!, "Battery", effectNameToId["Euphoric"]!!)
)

